### ISSUE TITLE
Question about ThreadProvider8 class behavior

### ISSUE THREAD

**Issue by juliojgd** [thunkware/virtual-threads-backport#2]
@maxxedev First of all, **great** work! This library comes very handy when you want to support pre-21 and 21+ concurrency focused code.

I have a question, the code in `ThreadProvider8` class, when you ask for a virtualThread or a `newThreadPerTaskExecutor`, as they don't exist in Java <21, it returns plain platform threads or an executor that return platform threads in a unbounded way.

I was thinking that it would be preferable that if you ask the `ThreadProvider8` class for VT related stuff, it should throw an `UnsupportedOperationExcception`. This to avoid people in Java < 21 thinking they are using's VT's (but they are not) so they create threads endlessly and break the JVM because so many platform threads created.

Is there any design decision involved for returning platform threads instead of failure in `ThreadProvider8` class?

https://github.com/thunkware/virtual-threads-backport/blob/c7a051af22dcbdbc7877bfc239861b738912e307/src/main/java/com/github/thunkware/ThreadProvider8.java#L42

Thanks in advance for your time 😄

**Comment by maxxedev** [comment]
I think if you don't want unbounded platform threads in Java20-, then you should not call those methods. You could write code like this:

```
ExecutorService executor = ExecutorTool.hasVirtualThreads()
    ? ExecutorTool.newVirtualThreadPerTaskExecutor()
    : Executors.newFixedThreadPool(10);
```

**Comment by maxxedev** [comment]
That said, there could be a way to force `newVirtualThreadPerTaskExecutor()` to throw exception on Java20- . Something like:
```
ExecutorService executor = ExecutorProvider.getInstance(VtMissingPolicy.THROW_EXCEPTION).newVirtualThreadPerTaskExecutor()
```

On Java20-, that code would fail but on Java21+, it would succeed.

**Comment by juliojgd** [comment]
> That said, there could be a way to force `newVirtualThreadPerTaskExecutor()` to throw exception on Java20- . Something like:
> 
> ```
> ExecutorService executor = ExecutorProvider.getInstance(VtMissingPolicy.THROW_EXCEPTION).newVirtualThreadPerTaskExecutor()
> ```
> 
> On Java20-, that code would fail but on Java21+, it would succeed.

It would be awesome to have a solution like that. Clean and clear 😄
